name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 12am UTC & 12am IST
    - cron: '* * * * *'
  push:
    branches:
      - master

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: nshimiyeemmy/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_OS: "True"
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROJECTS: "True"
          SHOW_TIMEZONE: "True"
          SHOW_EDITORS: "False"

